version: '3'

services:
    api:
        build: .
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
        links:
            - mongodb
        depends_on:
            - mongodb  
        command: npm start
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_USER="admin"
            - MONGODB_PASS="secret"
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet  