version: "3.3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "smart_api"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - mongodb
        links:
            - mongodb
        ports:
            - 3000:3000
        command: npm start
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_USER="admin"
            - MONGODB_PASS="secret"
        volumes:
            - ./mongo-data:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
volumes:
    mongo-data: